<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Catalogue de formation</title>
        <?php echo $this->headTitle(); ?>
        
        <?php echo $this->headMeta(); ?>
        
        <?php echo $this->headLink(); ?>
        
        <?php echo $this->headScript(); ?>
    </head>
    
    <body>
        <h1>Catalogue de formation</h1>
        <?php echo $this->layout()->content; ?>
    </body>
</html>